export const ROUTES = {
  MAIN: "/",
  BOOK_APPOINTMENT: "/book-appointment",
  APPOINTMENT_BOOKED: "/book-appointment/complete",
  SETUP: {
    MAIN: "/setup",
    CREATE_ADMIN_ACCOUNT: "/setup/create-admin-account",
    CHECK_EMAIL: "/setup/check-email",
  },
  SETUP_PASSKEY: "/confirm/setup-passkey",
  RESEND_CONFIRMATION: "/confirm/resend",
  LOGIN: "/login",
  LOGOUT: "/logout",
  DASHBOARD: {
    MAIN: "/dashboard",
    TENANTS: "/dashboard/tenants",
    CALENDAR: "/dashboard/calendar",
    STAFF: "/dashboard/staff",
    AGENTS: "/dashboard/agents",
    CHANNELS: "/dashboard/channels",
    ABSENCES: "/dashboard/absences",
    SETTINGS: "/dashboard/settings",
    ACCOUNT: {
      MAIN: "/dashboard/account",
      GENERAL: "/dashboard/account/general",
      PASSKEYS: "/dashboard/account/passkeys",
      CHANGE_EMAIL: "/dashboard/account/change-email",
      CHANGE_PASSPHRASE: "/dashboard/account/change-passphrase",
    },
  },
} as const;
